name: e_commerce
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  firebase_messaging: ^15.2.5
  firebase_core: ^3.13.0
  flutter_local_notifications: ^19.0.0
  cloud_firestore: ^5.6.6
  jiffy: ^6.4.3
  intl: ^0.20.2
  http: ^1.3.0
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  show_up_animation: ^2.1.2
  auto_animated: ^3.2.0
  flutter_polyline_points: ^2.1.0
  google_maps_flutter: ^2.10.1
  geocoding: ^3.0.0
  sqflite: ^2.4.1
  shared_preferences: ^2.5.3
  path: ^1.9.0
  qr_flutter: ^4.1.0
  grouped_list: ^6.0.0
  url_launcher: ^6.3.1
  dropdown_search: ^6.0.2
  badges: ^3.1.2
  font_awesome_flutter: ^10.8.0
  fluttericon: ^2.0.0
  dartz: ^0.10.1
  google_sign_in: ^6.2.2
  responsive_builder: ^0.7.1
  image_pickers: ^2.0.5+2
  lottie: ^3.2.0
  flutter_svg: ^2.0.17
  permission_handler: ^12.0.0+1
  geolocator: ^11.0.0
  flutter_launcher_icons: ^0.14.3
  file_picker: ^10.1.9
  dio: ^5.8.0+1
  googleapis_auth: ^1.6.0
  firebase_auth: ^5.5.4
  # location: ^7.0.1
  # android_intent_plus: ^5.3.0
  timeago: ^3.0.2
  firebase_database: ^11.3.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/icons/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
          weight: 900
    - family: PlayFairDisplay
      fonts:
        - asset: assets/fonts/PlayFairDisplay/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayFairDisplay/PlayfairDisplay-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/app_icon.png"
